import { createFileRoute } from "@tanstack/react-router";
import { Coffee, Moon, Sun, UtensilsCrossed } from "lucide-react";
import { BookingBand, PageIntro, SectionHeading } from "@/components/page-parts";
import terrace from "@/assets/river-terrace.png";
import river from "@/assets/beas-river-view.png";
import detail from "@/assets/lodge-detail.png";
import type { LucideIcon } from "lucide-react";
export const Route=createFileRoute("/cafe")({head:()=>({meta:[{title:"Cafe by Beas River | Swastika Lodge Manali"},{name:"description",content:"Enjoy breakfast, lunch and dinner with customizable meals and Beas River views at Swastika Lodge & Cafe in Manali."},{property:"og:title",content:"Cafe — Swastika Lodge Manali"},{property:"og:description",content:"Customizable meals and easy riverside moments in Aleo, Manali."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/cafe"}]}),component:CafePage});
const mealTimes: Array<[LucideIcon, string, string]> = [[Coffee,"Breakfast","A comfortable start before a day in Manali."],[Sun,"Lunch","A relaxed midday meal between local outings."],[Moon,"Dinner","Settle in after the mountains with an evening meal."]];
function CafePage(){return <><PageIntro eyebrow="Eat & unwind" title="A cozy cafe beside the Beas" copy="Begin slowly, pause between plans, and enjoy breakfast, lunch or dinner with customizable meals and river views."/><section className="mx-auto grid max-w-7xl gap-5 px-5 py-20 md:grid-cols-[1.35fr_0.65fr] lg:px-8"><img src={terrace} alt="Cafe terrace seating overlooking the Beas River" className="h-[520px] w-full object-cover image-lift"/><div className="grid gap-5"><img src={river} alt="Hot drink with a view of the Beas River and snowy mountains" className="h-[250px] w-full object-cover image-lift"/><img src={detail} alt="Warm handcrafted decor at Swastika Lodge cafe" className="h-[250px] w-full object-cover image-lift"/></div></section><section className="bg-muted"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionHeading eyebrow="Throughout the day" title="Made around your plans" copy="Meals can be customized. Ask the lodge directly about your preferences when booking."/><div className="mt-12 grid gap-px bg-border md:grid-cols-3">{mealTimes.map(([Icon,title,copy])=><article key={title} className="bg-background p-8"><Icon className="size-6 text-highlight"/><h2 className="mt-14 text-3xl">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{copy}</p></article>)}</div><div className="mt-12 flex items-center gap-3 text-sm text-primary"><UtensilsCrossed className="size-5"/><strong>Breakfast · Lunch · Dinner · Customizable meals</strong></div></div></section><BookingBand/></>}